
title: My Resume
url: 'http://rohanmallick.com'
baseurl: '/rohanmallick.com' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Rohan Mallick
tagline: Full Stack Salesforce Commerce Cloud Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mallickrohan08@gmail.com
phone: 012 345 6789
website: rohanmallick.com #do not add http://
linkedin: alandoe
github: mallickrohan08
twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
